id: P007925
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD159406
  title: གསུང་འབུམ། འཇམ་དབྱངས་རྒྱ་མཚོ།
  author: ''
  volumes:
    9ef3a062ca274a8e8c726f48b09e25c3:
      image_group_id: I1KG20615
      title: ''
      volume_number: 1
      total_pages: 0
    53d3cd69bbf9464f87f49ad1c2054634:
      image_group_id: I1KG20616
      title: ''
      volume_number: 2
      total_pages: 500
    bcc71a8035d547c7b5cc614983ad2392:
      image_group_id: I1KG20617
      title: ''
      volume_number: 3
      total_pages: 0
ebook_metadata:
  title: གསུང་འབུམ། འཇམ་དབྱངས་རྒྱ་མཚོ།
  author: ''
  sku: P007925
  cover: cover.jpg
  layers:
  - pagination
