id: P007925
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:49:36.299981
source_metadata:
  id: bdr:W1PD159406
  title: གསུང་འབུམ། འཇམ་དབྱངས་རྒྱ་མཚོ།
  author: ''
  volumes:
    36dfa8c925cb49048e27f05c704477db:
      image_group_id: I1KG20615
      title: Volume 1 of gsung 'bum/_'jam dbyangs rgya mtsho/
      volume_number: 1
      total_pages: 0
    44e350ec3d554bda9d695e7752dfb26a:
      image_group_id: I1KG20616
      title: Volume 2 of gsung 'bum/_'jam dbyangs rgya mtsho/
      volume_number: 2
      total_pages: 500
      base_file: v001.txt
    b40df51098a34e3e95c1335b65b2dc30:
      image_group_id: I1KG20617
      title: Volume 3 of gsung 'bum/_'jam dbyangs rgya mtsho/
      volume_number: 3
      total_pages: 0
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
