id: I353D3137
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T17:37:58+00:00'
last_modified: '2022-06-09T07:34:34.069293+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD159406
  title: གསུང་འབུམ། འཇམ་དབྱངས་རྒྱ་མཚོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    44AA:
      image_group_id: I1KG20615
      title: Volume 1 of gsung 'bum/_'jam dbyangs rgya mtsho/
      total_pages: 0
      order: 1
      base_file: 44AA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
